site_name: Physiopy
site_description: Physiopy
site_author: The Physiopy developers
site_url: https://physiopy.github.io
#google_analytics: ['UA-170131052-1', 'www.nipreps.org']

# Copyright
copyright: Copyright &copy; 2020

nav:
    - Home: index.md
    - Libraries:
      - Libraries: libraries.md
      - phys2bids: libraries/phys2bids.md
      - phys2denoise: libraries/phys2denoise.md
      - peakdet: libraries/peakdet.md
    - Community Practices:
      - Overview: practices/communityprac_overview.md
      - Setup: practices/communityprac_physsetup.md
      - Acquistion: practices/communityprac_collectphys.md
      - Processing: practices/communityprac_processphys.md
    - Community:
      - Welcome: community/index.md
      - Getting Started: community/gettingstarted.md
      - Contributor Guide: community/contributor-guide.md 
      - Open Datasets: community/open_datasets.md
      - Other Tools: community/other_tools.md
      - Code of Conduct: community/CODE_OF_CONDUCT.md
      - Team: community/team.md
    - OHBM 2023 Tutorials: ohbm23_tutorials.md
      


