site_name: Physiopy
site_description: Physiopy
site_author: The Physiopy developers
site_url: https://physiopy.github.io
#google_analytics: ['UA-170131052-1', 'www.nipreps.org']

# Copyright
copyright: Copyright &copy; 2020

nav:
    - Home: index.md
    - Libraries:
      - Libraries: libraries.md
      - phys2bids: libraries/phys2bids.md
      - phys2denoise: libraries/phys2denoise.md
      - peakdet: libraries/peakdet.md
    - Best Practices: 
        - Why Collect Phys Data?: best_practices.md
        - Setting up a Monitoring System: best_practices/phys_set_up.md
        - Acquring Physio Data: best_practices/collect_phys.md
        - Physio Processing: best_practices/process_phys.md
        - Physio/fMRI Analyses: best_practices/analyses_phys.md
    - Community:
      - Welcome: community/index.md
      - Getting Started: community/gettingstarted.md
      - Contributor Guide: community/contributor-guide.md 
      - Open Datasets: community/open_datasets.md
      - Code of Conduct: community/CODE_OF_CONDUCT.md
      - Team: community/team.md
      


