site_name: Physiopy
site_description: Physiopy
site_author: The Physiopy developers
site_url: https://physiopy.github.io
#google_analytics: ['UA-170131052-1', 'www.nipreps.org']

# Copyright
copyright: Copyright &copy; 2020

nav:
    - Home: index.md
    - Libraries:
        - Libraries: libraries.md
        - phys2bids: libraries/phys2bids.md
        - phys2denoise: libraries/phys2denoise.md
        - peakdet: libraries/peakdet.md
    - Best Practices: bestpractices.md
    - Community:
        - Welcome: community/welcome.md
        - Getting Started: community/gettingstarted.md
        - Contributors Guide: community/contributorsguide.md 
        - Open Datasets: community/opendatasets.md
        - Other Tools: community/other_tools.md
        - Code of Conduct: community/codeofconduct.md
        - Team: community/team.md
